name: Peter Park
favicon: null
layout_spectrum: 0.9432090818881989
typography_spectrum: 0.23164110025390983
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5198780850041658
  lightness: 0.26471634092740715
  saturation: 0.8548257735092193
  rhythmicContrast: 0.344399492489174
purpose: []
